chore(examples): compile & use scss in examples
patternfly/react-catalog-view pull request #73
Opened 2024-12-16 22:30 UTC by evwilkin

Closes #72 

This PR removes the custom stylesheets for each example and instead compiles the SASS locally to CSS, passes that to docs framework to be used in the examples, and then copies the compiled CSS to the dist directory.

Note: this will require design review - the shipped styles have not changed but the examples now differ in substantial ways such as blue borders at the top of Catalog Tiles.

2024-12-16 22:32 UTC, patternfly-build commented
Preview: https://react-catalog-view-pr-catalog-view-73.surge.sh

2024-12-20 17:38 UTC, christianvogt commented
The preview loses the hover treatment background. Is this intentional that the vertical tabs don't get this treatment?
![image](https://github.com/user-attachments/assets/c7511460-150c-4c48-b84d-cc03f7d54788)

2025-01-02 15:54 UTC, evwilkin commented
@mcoker & @andrew-ronaldson we should likely tag team this one, as the example styles being removed differ from the remaining styles shipped with the code.  

See @christianvogt comment above about background color on hover, this was hard-coded into the [example styles](https://github.com/patternfly/react-catalog-view/blob/main/packages/module/patternfly-docs/content/examples/verticalTab.css#L34) but does not exist in the [sass styles](https://github.com/patternfly/react-catalog-view/blob/main/packages/module/sass/react-catalog-view-extension/_vertical-tabs.scss#L24-L28).

2025-01-14 22:31 UTC, nicolethoen commented
I am seeing something misaligned and extra blue in some of the tiles

<img width="864" alt="Screenshot 2025-01-14 at 5 31 05 PM" src="https://github.com/user-attachments/assets/0a8873b1-94f7-4c64-a8fe-1fc860a60b27" />

2025-08-19 19:10 UTC, nicolethoen commented
<img width="1571" height="951" alt="Screenshot 2025-08-19 at 3 09 48 PM" src="https://github.com/user-attachments/assets/930c611f-4b71-46c1-a4b9-fbc353204351" />

I cleaned up this PR and took the time to build out the designed catalog-view demo which had never been implemented. It turned into a good use case to make sure the styles are looking okay.

2025-08-20 12:48 UTC, andrew-ronaldson requested changes
The demo looks good, thanks for making that.
I noticed the vertical tabs look different from our [Figma file](https://www.figma.com/design/MSr6kVEOuAxmPOkjg7x8PO/PatternFly-6--Patterns---Extensions?m=auto&node-id=2387-45696&t=Aj7zNxwO4VwUa2nH-1) and I need to add a selected + hover variant since it is missing right now.

<img width="1686" height="937" alt="Screenshot 2025-08-20 at 9 42 19 AM" src="https://github.com/user-attachments/assets/1da06b68-47cc-4997-b0b1-17405bf13733" />

2025-08-21 18:04 UTC, nicolethoen commented
@andrew-ronaldson in the demo - the sidebar panel appears to be more like advanced filtering with checkboxes - not tabs. What is the intended relationship between the sidebar items/tabs and the catalog tiles? Would i be applying this selected state when teh checkbox is selected?

2025-09-16 14:03 UTC, andrew-ronaldson approved these changes
Demo looks good

2025-09-18 14:55 UTC, merged